name: speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability.
version: 6.6.1
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface: ^2.2.0
  speech_to_text_macos: ^1.1.0
  json_annotation: ^4.8.1
  clock: ^1.1.1
  pedantic: ^1.11.1
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  fake_async: ^1.3.1
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
