name: speech_to_text
description: A Flutter plugin that exposes device specific speech to text recognition capability.
version: 6.6.1
homepage: https://github.com/csdcorp/speech_to_text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  clock: ^1.1.1
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  speech_to_text_platform_interface: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.9
  fake_async: ^1.3.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  mockito: ^5.4.4
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
